Import('library_env')

#Return all of the object files generated so that we can build the progra.
objs = []

srcfiles =  Glob("*.c") + \
            Glob("cdb/*.c")

for src in srcfiles:
    objs.append(library_env.Object(src))

library_env.StaticLibrary(library_env['OUTPUT'], objs)
