ModuleName = "test12";
ModuleVersion = "1.2.3";
APIVersion = "1.2";

RandomVariable = 0x100;

0x12ab: _test(0, no);
64000: test2(1, yes);


required config uint8_t testvar1;
required config char testvar2[26];

#Missing optional word
config uint32_t testvar3;
