ModuleName = "test12";
ModuleVersion = "1.2.3";
APIVersion = "1.2";

RandomVariable = 0x100;

#Endpoints you can call on this module
0x12ab: _test(0, no);
64000: test2(1, yes);

#Required configuration variables that need to be set
0x12ba: required config uint8_t testvar1;
0xabcd: required config char testvar2[26];

#Optional configuration variables that can be set
0x1235: optional config uint32_t testvar3 = 0x1202341;
0x1236: optional config char testvar4[15] = "test string";
0x5234: optional config char testvar5[30] = "http://www.test.com";