name: "Run tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  test-windows:
    name: test-windows py${{ matrix.python }}
    runs-on: windows-2019
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      matrix:
        python: ["3.6", "3.7", "3.8"]

    steps:
      - name: Cancel duplicate jobs
        uses: styfle/cancel-workflow-action@0.9.0
        if: ${{ !env.ACT }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: "make gcc dir"
        run: mkdir c:\gcc

      - name: "Download gcc-arm"
        run: |
          curl -L -o gcc-arm-none-eabi.zip "https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-win32.zip?revision=df1b65d3-7c8d-4e82-b114-e0b6ad7c2e6d?product=GNU%20Arm%20Embedded%20Toolchain,ZIP,,Windows,7-2017-q4-major"

      - name: "unzip gcc"
        run: unzip -o gcc-arm-none-eabi.zip -d c:\gcc\

      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip && pip install -U setuptools tox

      - name: 'Run tests'
        run: |
          set PATH=%PATH%;c:\gcc\bin
          tox -r -e py${{ matrix.python }}-mac_windows
        
  test-macOS:
    name: test macOS py${{ matrix.python }}
    runs-on: macos-10.15
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      matrix:
        python: ["3.6", "3.7", "3.8"]

    steps:
      - name: Cancel duplicate jobs
        uses: styfle/cancel-workflow-action@0.9.0
        if: ${{ !env.ACT }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip && pip install -U setuptools tox && pip install -r build_requirements.txt 

      - name: "Install GCC with brew"
        run: |
          brew tap PX4/px4
          brew install px4/px4/gcc-arm-none-eabi
          which arm-none-eabi-gcc

      - name: 'Run tests'
        run: tox -r -e py${{ matrix.python }}-mac_windows
